services:
  master:
    image: ghcr.io/planeturban/packa
    ports:
      - "9000:9000"
    volumes:
      - ./packa.toml:/data/packa.toml:ro
      - master-data:/data
#      - /mnt/data:/mnt/data:ro # Path to data directory on host, read-only
    restart: unless-stopped

  worker:
    image: ghcr.io/planeturban/packa
    environment:
      PACKA_ROLE: worker
      PACKA_WORKER_MASTER_HOST: master
      PACKA_WORKER_ADVERTISE_HOST: worker
    ports:
      - "8000:8000"
    volumes:
      - ./packa.toml:/data/packa.toml:ro
      - worker-data:/data
#      - /mnt/data:/mnt/data # Path to data directory on host.
#      - /mnt/output:/mnt/output # Path to output directory on host. Needed if you don't want to overwrite the source files.
    depends_on:
      - master
    restart: unless-stopped

  web:
    image: ghcr.io/planeturban/packa
    environment:
      PACKA_ROLE: web
      PACKA_WEB_MASTER_HOST: master
    ports:
      - "8080:8080"
    volumes:
      - ./packa.toml:/data/packa.toml:ro
      - web-data:/data
    depends_on:
      - master
    restart: unless-stopped

volumes:
  master-data:
  worker-data:
  web-data:
