services:
  master:
    image: ghcr.io/planeturban/packa
    environment:
      PACKA_ROLE: master
      PACKA_CONFIG: /etc/packa/packa.toml
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
    ports:
      - "9000:9000"
    volumes:
      - ./packa.toml:/etc/packa/packa.toml:ro
      - master-data:/data
#      - /mnt/data:/mnt/data:ro # Path to data directory on host, read-only
    restart: unless-stopped

  worker:
    image: ghcr.io/planeturban/packa
    environment:
      PACKA_ROLE: worker
      PACKA_CONFIG: /etc/packa/packa.toml
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
      PACKA_WORKER_MASTER_HOST: master
      PACKA_WORKER_ADVERTISE_HOST: worker
      PACKA_EXTRA_ARGS: "--insecure-no-tls"
    ports:
      - "8000:8000"
    volumes:
      - ./packa.toml:/etc/packa/packa.toml:ro
      - worker-data:/data
#      - /mnt/data:/mnt/data # Path to data directory on host.
#      - /mnt/output:/mnt/output # Path to output directory on host.
    depends_on:
      - master
    restart: unless-stopped

  web:
    image: ghcr.io/planeturban/packa
    environment:
      PACKA_ROLE: web
      PACKA_CONFIG: /etc/packa/packa.toml
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
      PACKA_WEB_MASTER_HOST: master
      PACKA_EXTRA_ARGS: "--insecure-no-auth"
    ports:
      - "8080:8080"
    volumes:
      - ./packa.toml:/etc/packa/packa.toml:ro
      - web-data:/data
    depends_on:
      - master
    restart: unless-stopped

volumes:
  master-data:
  worker-data:
  web-data:
