apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: packa-master
  namespace: packa
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["packa-bootstrap-token"]
    verbs: ["get", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: packa-master
  namespace: packa
subjects:
  - kind: ServiceAccount
    name: packa-master
    namespace: packa
roleRef:
  kind: Role
  name: packa-master
  apiGroup: rbac.authorization.k8s.io
