apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - master/serviceaccount.yaml
  - master/rbac.yaml
  - master/secret-bootstrap.yaml
  - master/statefulset.yaml
  - master/service.yaml
  - master/service-lb.yaml
  - worker/statefulset.yaml
  - worker/service.yaml
  - web/deployment.yaml
  - web/service.yaml
  - web/ingress.yaml
