apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: packa-dev

resources:
  - ../../base

images:
  - name: ghcr.io/planeturban/packa
    newName: registry.k.int/packa/packa
    newTag: latest

patches:
  - path: patch-services.yaml
  - path: patch-web-init.yaml
