apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: packa
spec:
  template:
    spec:
      containers:
        - name: web
          env:
            - name: PACKA_WEB_TLS_CERT
              value: /tls/tls.crt
            - name: PACKA_WEB_TLS_KEY
              value: /tls/tls.key
          volumeMounts:
            - name: tls
              mountPath: /tls
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: packa-tls
