apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      initContainers:
        - name: bootstrap
          imagePullPolicy: Always
      containers:
        - name: web
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: master
spec:
  template:
    spec:
      containers:
        - name: master
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: worker
spec:
  template:
    spec:
      containers:
        - name: worker
          imagePullPolicy: Always
